### ISSUE TITLE
Flake fails

### ISSUE THREAD

**Issue by mtausig** [cfv-project/cfv#15] opened 2020-10-06 22:12 UTC
Running the code style checker `flake` as expected by the CI script currently causes some errors:

```bash
$ flake8 --exclude=build,venv --ignore= --max-line-length=200 --max-complexity=75 --show-source --statistics .
./lib/cfv/common.py:738:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/common.py:900:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/common.py:1400:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/common.py:1505:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/common.py:1537:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/common.py:1572:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/common.py:1649:34: E741 ambiguous variable name 'l'
    def do_test_chksumline(self, l):
                                 ^
./lib/cfv/osutil.py:112:78: E741 ambiguous variable name 'I'
def strippath(filename, num='a', _splitdrivere=re.compile(r'[a-z]:[/\\]', re.I)):
                                                                             ^
./lib/cfv/strutil.py:6:14: E741 ambiguous variable name 'l'
def safesort(l):
             ^
./test/cfvtest.py:49:26: E741 ambiguous variable name 'l'
    def writelines(self, l):
                         ^
10    E741 ambiguous variable name 'l'
```

**Comment by lxp** [comment] 2020-10-06 22:38
Thanks for opening the issue, but it looks like I was a few seconds faster. Duplicate of #14

**Closed by lxp** 2020-10-06 22:38 UTC
